language: node_js
node_js:
  - node
  - 7
  - 6
  - 5
  - 4

env:
  - NODE_ENV=travis

before_install:
  - npm install istanbul mocha coveralls codacy-coverage -g

after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage

notifications:
   email:
     - flaesch.arnaud@esgi.fr